In [1]:
# we will always import these packages at the top of our code
# magic code which let's us see graphs 'inline' in the notebook
%matplotlib inline 
import numpy as np # numpy helps us do maths
import pandas as pd # pandas helps us load files and databases - think of it as a much better excel spreadsheet
import matplotlib.pyplot as plt # matplotlib helps us plot
from astropy.cosmology import Planck15 as cosmo # helps us do cosmology

# Reading and writing using numpy and pandas

In this notebook we will very simply create, write and read a text file in numpy and in pandas. 

There is no practice question on this topic.

### Numpy savetxt and loadtxt

In [2]:
# making some data for us to write out
array_x=np.array([0,1,2,3])
array_y=np.array([0,1,4,9])

Let's just examine quickly how we might 'print out' this data - we can do it in rows or columns

In [10]:
print(array_x, array_y)

[0 1 2 3] [0 1 4 9]


In [11]:
print(np.c_[array_x, array_y])

[[0 0]
 [1 1]
 [2 4]
 [3 9]]


In [13]:
# write the file use numpy savetxt we'll do this in two ways - go to your drive where this notbook is running (on your laptop, sciserver or google colab) open the file and look at the format of the output ( np.c_[] gives columns of data)
np.savetxt('my_file1.txt', [array_x, array_y])
np.savetxt('my_file2.txt', np.c_[array_x, array_y])

In [14]:
# we usually want the column data as it is easier to use - let's read it in
matrix=np.loadtxt('my_file2.txt')
print(matrix)

[[0. 0.]
 [1. 1.]
 [2. 4.]
 [3. 9.]]


In [15]:
# but we can also 'unpack' the data into separate columns immediately
x, y=np.loadtxt('my_file2.txt', unpack=True)
print(x)
print(y)

[0. 1. 2. 3.]
[0. 1. 4. 9.]


## Pandas read_csv and to_csv

pandas is a package which is helpful for when we are using 'database' or 'spreadsheet' style data. Think of it like a much much much better excel or google sheets!

In [34]:
data = pd.read_csv('my_file2.txt', sep=' ', names=(['x','y']), usecols=[0, 1], index_col=False)

In [35]:
# lets look at how pandas displays data
data

x    y
0  0.0  0.0
1  1.0  1.0
2  2.0  4.0
3  3.0  9.0

pandas can easily handle names on the tops of columns already written into the files - they will appear at the top of these dataframes and then we wouldn't need to specify names=. Also note that the default separation between values is expected to be comma separated so we need to define what the delimiter is using sep=' ' if we have something else like white space. See the help docs here: https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html  

In [38]:
# let's write the data back out as a csv file
data.to_csv('my_file2.csv')